### ISSUE TITLE
Increase coverage

### ISSUE THREAD

**Issue by jlaehne** [LumiSpy/lumispy#133]
We have some low hanging fruit in increasing the test coverage of LumiSpy:

- [x] `px_to_nm_grating_solver` in `signals/luminescence_spectrum.py` is not covered [See codecov, lines 291-310]
- [x] For `to_eV` and `to_invcm` in `signals/luminescence_spectrum.py`, the case where the variance is a single `int/float` is not covered when `inplace=True`. [See codecov, lines 154-161 & 309-316](https://app.codecov.io/gh/LumiSpy/lumispy/blob/7eed9e4e96e2e24379ceadb34a8349938b101338/lumispy/signals/luminescence_spectrum.py)
- [x] `scale_by_exposure` in `signals/common_luminescence.py` is missing coverage for the situation where `("Signal.quantity") == "Intensity (Counts)"` [See codecov, lines 154-155](https://app.codecov.io/gh/LumiSpy/lumispy/blob/7eed9e4e96e2e24379ceadb34a8349938b101338/lumispy/signals/common_luminescence.py)
- [x] `remove_spikes` in `signals/cl_spectrum.py` is missing coverage for `show_diagnosis_histogram` [See codecov, line 92](https://app.codecov.io/gh/LumiSpy/lumispy/blob/7eed9e4e96e2e24379ceadb34a8349938b101338/lumispy/signals/cl_spectrum.py)
- [x] `solve_grating_equation` in `utils/axes.py` is missing coverage for axis being non-uniform `DataAxis` [See codecov, line 485](https://app.codecov.io/gh/LumiSpy/lumispy/blob/7eed9e4e96e2e24379ceadb34a8349938b101338/lumispy/utils/axes.py)

- `remove_background_from_file` misses some tests for warnings/errors, but as it will be deprecated is not worth implementing.

**Comment by jordiferrero** [comment]
Coverage 100%
