### ISSUE TITLE
Webhook failing

### ISSUE THREAD

**Issue by jlaehne** [LumiSpy/lumispy#136]
As you set it up @jordiferrero, we have a webhook for read-the-docs running that seems to be regularly failing:
https://github.com/LumiSpy/lumispy/settings/hooks/341637685?tab=deliveries

The rtd integration seems to work otherwise. Any ideas how to fix that?

**Comment by jordiferrero** [comment]
I don't understand what you mean. Could you maybe expand a bit?
Is the fail produced every time we change the docs?

**Comment by jlaehne** [comment]
You set it up, so I thought you have a better idea. I just saw that under the link above there is a long list of failures. It makes the impression that it is every time a new commit that affects the docs is uploaded.

Just realized that there is a second functioning webhook for readthedocs:
https://github.com/LumiSpy/lumispy/settings/hooks/341638412?tab=deliveries
(the `Payload URL` is different)

So probably, we can just delete the failing one?

**Comment by jordiferrero** [comment]
Yes indeed. That was when I was setting it up and the first time I did it, I messed it up with the URL name. Then I fixed it. But it seems the old webhook was still linked to the repo.
Fixed now by removing failing webhook.
Thanks!
