### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by jordiferrero** [LumiSpy/lumispy#166]
#### Describe the bug
The read the docs equations are broken.
It does not show the "parsed" images of the maths equation.

The change that caused it is #163 by @jlaehne

![image](https://user-images.githubusercontent.com/9082687/206695971-fe75e92f-b95d-4d74-9b38-4c124bfac47d.png)

https://docs.lumispy.org/en/latest/user_guide/signal_axis.html
I tried to figure out what changed, but I am not sure... can you have quick look?

**Comment by jlaehne** [comment]
On first sight, I do not see how #163 should have introduced that, but the same problem was reported for the HyperSpy documentation on gitter: https://gitter.im/hyperspy/hyperspy?at=6381155b655bc46025e30c63
and I then mentioned it in https://github.com/hyperspy/hyperspy/pull/3050#issuecomment-1328049783

But it has not been resolved there either yet. I suspect it is something changed upstream on how sphinx handles latex-type equations.

**Comment by jordiferrero** [comment]
OK. Then I guess there is nothing we can currently do... Thanks for the explanation.

**Comment by jlaehne** [comment]
Well, I think we should try to find out if it is a configuration issue of the imgmath plugin to sphinx.
