### ISSUE TITLE
Fix test for `remove_spikes`

### ISSUE THREAD

**Issue by jlaehne** [LumiSpy/lumispy#185]
Some recent update to HyperSpy or an upstream library breaks the test for automatic peak removal:

```
>       np.testing.assert_almost_equal(s3.data[0, 2, 29], 1, decimal=5)
E       AssertionError: 
E       Arrays are not almost equal to 5 decimals
E        ACTUAL: 2.000005802611809
E        DESIRED: 1
```

You can see the full output here: https://github.com/LumiSpy/lumispy/actions/runs/4451990112/jobs/7819241076

The smaller of the two artificial peaks is not caught on every run, if the `threshold` is `auto`.

I commented out line 70 and 85 in `test_cl_spectrum.py` to make the tests run through in #184.
Also I set `decimal=4` (instead of `5`) in all assertions as it was loosing accuracy on some runs.

So far, I have not found why the numerics suddenly seem to be less reliable.

In principle, the function should still run, but it seems to be less robust.

Any idea @jordiferrero or @ericpre

**Comment by Attolight-NTappy** [comment]
Hello!

Just wanted to share that  the incriminated test runs fine with my configuration, so I don't think it is an upstream library modification issue:

lumispy 0.2.3.dev0 (main branch)
hyperspy 1.8.0.dev0 (both RELEASE_next_minor and RELEASE_next_patch branches)

```
============================= test session starts =============================
collecting ... collected 2 items

test_cl_spectrum.py::TestCLSpectrum::test__make_signal_mask 
test_cl_spectrum.py::TestCLSpectrum::test_remove_spikes 

======================== 2 passed, 3 warnings in 3.57s ========================

Process finished with exit code 0
PASSED       [ 50%]PASSED           [100%]
```

I have python 3.10.9 and numpy 1.23.5.
