### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by ericpre** [LumiSpy/lumispy#24]
It would be good to set up continuous integration for this repository.

It is well documented online but as a starting point it may be worth having a look:
https://github.com/hyperspy/ci-scripts

**Comment by jordiferrero** [comment]
@ericpre If you are happy with this CI implementation, please cloase this issue. Otherwise we can work on it further.

**Comment by ericpre** [comment]
I have wrote a couple of comments on #30. Having Azure pipeline would be worth to test on the 3 main platforms.

**Comment by jordiferrero** [comment]
Working on adding Azure pipeline in #33 .

**Comment by jordiferrero** [comment]
Now both Travis and Azure pipelines work well.
However, I would ask if you could quickly check if the Azure pipeline is doing the tasks it is supposed to do (so far it simply runs the same `pytest` scripts as Travis), @ericpre .

**Comment by ericpre** [comment]
> However, I would ask if you could quickly check if the Azure pipeline is doing the tasks it is supposed to do (so far it simply runs the same `pytest` scripts as Travis), @ericpre .

Yes, both are working, but I would suggest to do the following:
- travis test `pip` only install using packages from pypi
- azure test `conda` environment

At the moment, it azure is doing almost the same as travis, using packages from pypi instead of conda packages. This is because you are missing the files defining what package to install in the conda environment (see https://github.com/hyperspy/ci-scripts#conda-environment).

Since pip and conda are the main way to install python packages, this is useful to check that both are working fine. For a pure python library, this may sounds overkill but it has the advantage that it checked that the dependencies are working fine in both cases. Also packages are usually release first on pypi before being available on anaconda cloud and if the update of a dependency break the test suite, it should come up first on travis.

As mentioned in https://github.com/hyperspy/ci-scripts/pull/1, I will follow up with a PR to clarify these points.

> I also don't seem to understand why in [here](https://github.com/LumiSpy/lumispy/blob/35e888cb1963535b41a6433f6cdf4dc757f1b578/azure-pipelines.yml#L22) if I set as `endpoint: lumispy` (so the organisation under my username in DevOps) the pipeline fails. As far as I know, both my username (`jordiferrero`) and the organisation (`lumispy`) should have full access to Github from Azure...

Can you please point out to a specific build?

**Comment by jordiferrero** [comment]
> > I also don't seem to understand why in [here](https://github.com/LumiSpy/lumispy/blob/35e888cb1963535b41a6433f6cdf4dc757f1b578/azure-pipelines.yml#L22) if I set as `endpoint: lumispy` (so the organisation under my username in DevOps) the pipeline fails. As far as I know, both my username (`jordiferrero`) and the organisation (`lumispy`) should have full access to Github from Azure...
> 
> Can you please point out to a specific build?

Here are the examples:
- [Here](https://dev.azure.com/Lumispy/lumispy/_build/results?buildId=28&view=results) the build was made setting `endpoint: jordiferrero`. All good.

- [Here](https://dev.azure.com/Lumispy/lumispy/_build/results?buildId=29&view=results) the only change was to add `endpoint:lumispy`. 
This suddenly raises the following error:
`/azure-pipelines.yml: Could not get the latest source version for repository hyperspy/ci-scripts hosted on https://github.com/ using ref refs/heads/master. GitHub reported the error, "Not Found"`
