### ISSUE TITLE
[Attilight] Change flow to include `.sur` file loading

### ISSUE THREAD

**Issue by jordiferrero** [LumiSpy/lumispy#38]
With the addition of `.sur` file reading in Hyperspy 1.6, the loading functions for the `HYPMap.bin` are no longer necessary.
I will sort this out soon, cleaning up the `io-plugins` section.

**Comment by jlaehne** [comment]
I will have a look at your changes as soon as I find the time.

**Comment by jordiferrero** [comment]
I have opened 2 PR to deal with that.
But I haven't had time to actually make the changes I have in mind yet.
I hope to do it next Sunday. Will let you know when I have it ready so you can give your advice.  Thanks!

**Comment by jlaehne** [comment]
No rush, I'll be on vacation the next two weeks.
