### ISSUE TITLE
Fix coverage badge

### ISSUE THREAD

**Issue by jlaehne** [LumiSpy/lumispy#62]
The coveralls badge is claiming 0% coverage, though when you check out the details we are at >90%. Probably something in the coveralls settings?

Or use codecov instead of coveralls, like HyperSpy?

**Comment by ericpre** [comment]
The codecov seems to work well with HyperSpy and the corresponding github annotations on the changes of the pull request are very convenient!

**Comment by jlaehne** [comment]
Nice, the badge works.
