### ISSUE TITLE
LumiSpy logo

### ISSUE THREAD

**Issue by jlaehne** [LumiSpy/lumispy#65]
Any ideas for a LumiSpy logo?

One idea I had was using this map of emission energy around a dislocation in GaN, but any further ideas are welcome.
![image](https://user-images.githubusercontent.com/7076057/112737796-5d997280-8f5d-11eb-92a4-bb02e852cde6.png)

**Comment by jordiferrero** [comment]
Your last comment triggered one of my hobbies, computer design.
I made some sketches of ideas I also had a while ago combining the *lambda* and the *spectral colours* (like it is not that important... but it is fun!)

Happy to combine my ideas with your GaN, let me know what you think :-)
<img width="3043" alt="Asset 15@2x" src="https://user-images.githubusercontent.com/9082687/112761294-edd9c500-8ffa-11eb-85c2-6a4e34f0db2c.png">

**Comment by ericpre** [comment]
@jordiferrero, some very good ideas in your design! Columns 1 is very nice. Would it work to make the `S` a snake?

I am not very good at this, but with some help, we gave a go and here are some additional ideas to add the mix:

![Screenshot 2021-03-28 at 18 42 37](https://user-images.githubusercontent.com/11851990/112765129-9f7cf400-9003-11eb-95ed-5d901ddd13be.png)

Some of it appears not to be very good, for example, I had hope that something good will come out of putting waves/snake but it turns out just to look like a parachute...

**Comment by jlaehne** [comment]
@jordiferrero, I like the typography and the simpleness of columns 1&2, with a clear preference for the black version (not only because I use the dark theme on github, but also because lumi-labs tend to be dark, which is less the case for CL though)!

1B is nice, because I think including the full name is good. On the other hand, we need a square logo for the icon. Either having 2B as a compact version or madifying the logo towards a more squared shape.

By the way, you would need to switch purple and blue ;-)

From @ericpre I like the wave idea (the parachute looks like a detector, but looks too playful for a logo probably), though the lines might have to be a bit thicker to look good. How would it look to combine 1B with the waves (still with a bit of offset to the dot of the i, which could be slightly enlarged, but not too much) - could also help going closer to a square aspect ratio of the overall logo?

**Comment by jordiferrero** [comment]
I love all your comments! I will put together a version similar to 1B with waves and will share again so we can vote again!
Thanks for the involvement :-)

**Comment by jordiferrero** [comment]
Here we go again...
<img width="1960" alt="Asset 16@2x" src="https://user-images.githubusercontent.com/9082687/112862097-b3812e00-90b5-11eb-8b7d-d908f2843150.png">

I really like the snake hint... after all it's Python

**Comment by jlaehne** [comment]
I first thought soemthing is weird, before I realized the snakehead .

B3 looks too much like hair under static charge.

B2 looks more like waves. Would it be possible for the lines of the waves to be thinner towards the center? Angles have to be polished a little probably, but I tend towards that direction. The flower in "B1" is nice and simple, but I like the idea of light and waves.

**Comment by ericpre** [comment]
The waves does work very well... but the snack is very nice!

**Comment by jlaehne** [comment]
I could not help playing a bit myself:

![image](https://user-images.githubusercontent.com/7076057/112910509-c7e41b80-90f3-11eb-9302-fef895fe2796.png)

**Comment by jordiferrero** [comment]
I really like the frequency differences between the colours!

I'm happy with the C2 (works better when you zoom out and see the logo in small as lines are thicker) and then A2.

Do you have the editable file? 
I think I would only change a few details (the end of the orange, yellow and green have a rounded head while the others don't) and for C2, the red wavelength is a bit too close to the S in my opinion.  But these are very minor things :-) 
Happy to stick to that!

**Comment by jordiferrero** [comment]
![logo_final_march_2021](https://user-images.githubusercontent.com/9082687/113130101-f4935280-921b-11eb-925e-d6de5883eaa5.png)

Final version?

**Comment by jlaehne** [comment]
Almost, for the orange (and maybe also yellow and green) the last segment is a bit too straight, could you make it a bit more like on the red?

But otherwise, really cool!

I fear, the square version would get too small when used as avatar, would the `λy` version still work with the new wavy lines? I fear the purple would get too close to λ, but maybe you can make it work somehow?

**Comment by ericpre** [comment]
Agree, this is nice. I was also thinking the same about using the `λy` version for the square aspect ratio.

**Comment by jordiferrero** [comment]
A- Square not simplified:
![logo_sq_final_march_2021](https://user-images.githubusercontent.com/9082687/113144520-9d967900-922d-11eb-8f27-191539ae2174.png)
B- Square simplified 1:
![logo_sq_final_march_2021_2](https://user-images.githubusercontent.com/9082687/113144200-4abcc180-922d-11eb-9263-fb46d97610cc.png)
C- Square simplifed 2:
![logo_sq_final_march_2021_3](https://user-images.githubusercontent.com/9082687/113144203-4b555800-922d-11eb-8dab-403288a34225.png)

D- Rectangular logo (normal)
![logo_final_march_2021](https://user-images.githubusercontent.com/9082687/113144204-4b555800-922d-11eb-8435-7e5a2a974bf7.png)

Final version now?

**Comment by jlaehne** [comment]
+1 for B & D

Does not hurt having the white BG version as svg somewhere (though if we have the svg somewhere, which we should, it can be easily created anytime). I would prefer to discourage use of the white BG version - so not to publish it in equal terms.

**Comment by jlaehne** [comment]
How about including an svg of the logo in the repository and adding the image as headline to the Readme, then it would also appear on e.g. Pypi.

**Comment by jordiferrero** [comment]
All completed now.
Files are in the repo.
