### ISSUE TITLE
Azure pipeline failure

### ISSUE THREAD

**Issue by ericpre** [LumiSpy/lumispy#71]
The failure on azure pipeline are temporary, because the `dask-core` package is broken on anaconda defaults. The package on conda-forge is fine but CI is setup with the anaconda defaults channels as higher priority than conda-forge. This should be temporary until https://github.com/AnacondaRecipes/dask-core-feedstock/pull/2 is merged and the packages available on the server.

**Comment by jlaehne** [comment]
Thanks, I was already wondering.

**Comment by ericpre** [comment]
This is now fixed.
