### ISSUE TITLE
Updated map method in HyperSpy v1.6.2

### ISSUE THREAD

**Issue by jlaehne** [LumiSpy/lumispy#75]
Indeed, the failure are related to changes in the `map` method:
```python
ValueError: The size of the navigation_shape for the kwarg shift (<(100,)> must be consistent with the size of the mapped signal <(10, 10)>
```
This point out to an argument which doesn't have the right shape. It is fairly likely that ambiguous usage of `map` such as this one are not allowed anymore.

_Originally posted by @ericpre in https://github.com/LumiSpy/lumispy/issues/68#issuecomment-826840816_

**Comment by ericpre** [comment]
Fixed in #77.
