### ISSUE TITLE
Fix image on pypi

### ISSUE THREAD

**Issue by ericpre** [LumiSpy/lumispy#86]
The nice lumispy logo doesn't play well with pypi: https://pypi.org/project/lumispy.

To figure out how to fix it, [`twine check`](https://twine.readthedocs.io/en/latest/#twine-check) and https://packaging.python.org/guides/using-testpypi may be useful.

**Comment by jlaehne** [comment]
Thanks, I'll have a look into it. One easily finds similar discussions:

https://github.com/pypa/warehouse/issues/5246

https://stackoverflow.com/questions/41983209/how-do-i-add-images-to-a-pypi-readme-that-works-on-github

**Comment by jlaehne** [comment]
Basically, we used a local reference to the image. With the `raw`-link to github, the image should be universally accessible.
