### ISSUE TITLE
Rename `master` to `main`

### ISSUE THREAD

**Issue by ericpre** [LumiSpy/lumispy#87]
See https://github.com/github/renaming for details.

The `master` branch simply needs to be renamed but I open an issue to avoid surprises!

**Comment by jlaehne** [comment]
If no one objects, I would wait a few days and then do the rename.

**Comment by jlaehne** [comment]
Done.

Everyone locally still using the master branch now needs to rename their local clones:

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```

**Comment by jlaehne** [comment]
And rename the branch name in your fork of course.
